version: "3"

services:
  app:
    build: .
    image: auction-app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8080:8000
  celery:
    image: auction-app
    command: bash -c "celery -A auction worker -l INFO"
    env_file:
      - .env
    ports:
      - 8000:8000

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  rabbit:
    image: rabbitmq:3
