# Generated by Django 3.1.7 on 2021-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Finished')], default=1),
        ),
    ]
